### ISSUE TITLE
Возврат к началу ленты по кнопке обновления

### ISSUE THREAD

**Issue by skobkin** [Tishka17/Point.im-Android#11]
Нужно сделать возврат к началу ленты по кнопке обновления.
Сейчас если долго листать вниз, когда хочешь почитать что-то новое, приходится очень много листать вверх. Чаще всего перемотку вверх объединяют вместе с обновлением ленты - это был бы неплохой вариант. Хотя и отдельно это реализовать тоже можно для гибкости. Впрочем, для второго варианта я не видел красивых решений.

**Comment by Tishka17** [comment]
дубль #4
