### ISSUE TITLE
При открытии проги нет автообновления

### ISSUE THREAD

**Issue by veresk** [Tishka17/Point.im-Android#3]
Собственно, пока не обновишь страничку - пустой список.

**Comment by skobkin** [comment]
ИМХО, автоматическое обновление лучше сделать опцией.
А без неё автоматически обновлять ленту только если она ещё пустая (первый запуск или там изменение формата хранения). Либо сделать из этого ещё одну опцию. Хотя тогда можно превратиться в Miranda IM.

**Comment by skobkin** [comment]
Но оно должно быть в любом случае - хотя бы опциональным. Сейчас то обновляет, то не обновляет.

**Comment by Tishka17** [comment]
Убрал автообновление, зато починил загрузку из кэша.

**Comment by skobkin** [comment]
Сделай опцией. Обычно сверху находится то, что я уже читал.

**Comment by Tishka17** [comment]
Сделаю, что при открытии нового окна будет автоапдейт, а если из списка недавних - просто кэш
