### ISSUE TITLE
Не полная прокрутка при обновлении

### ISSUE THREAD

**Issue by veresk** [Tishka17/Point.im-Android#4]
При обновлении странички текст размещается в каком-то собственном недомыслии: не на первом посте, но и не там, где закончил читать. Обычно на посте 2-3 показ идёт.

**Comment by Tishka17** [comment]
Хм. Вроде - на том месте, где закончил. В любом случае нужна прокрутка вверх.

**Comment by veresk** [comment]
В том то и дело - не докручивает до верха.

14 января 2015 г., 9:07 пользователь Tishka17 <notifications@github.com>
написал:

> Хм. Вроде - на том месте, где закончил. В любом случае нужна прокрутка
> вверх.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Tishka17/Point.im-Android/issues/4#issuecomment-69873359>
> .
>



-- 
________
С уважением, Вереск

**Comment by veresk** [comment]
Вот так это выглядит, вверху ещё 2 сособщения.

![screenshot_2015-01-14-20-01-01](https://cloud.githubusercontent.com/assets/2063025/5754694/39ee2ffa-9cad-11e4-86fa-13f223fec61f.png)

**Comment by Tishka17** [comment]
Прошу проверить в 2.3
