### ISSUE TITLE
All гоняет по кругу первую страницу, подгрузка не работает.

### ISSUE THREAD

**Issue by veresk** [Tishka17/Point.im-Android#6]
Аааа, чуть не умер на прокрутке ленты all! Она после догрузки начало загружает.

**Comment by Tishka17** [comment]
Судя по всему метод API работает игнорирует параметр. Надо на сервер баг написать

**Comment by skobkin** [comment]
А я уж было тоже хотел багреп писать:
http://www.youtube.com/watch?v=nmC1orVxTNo
